"""
main.py

- 1分ごとに `fitbit_sampler.fetch_day`（full_day_updater）で当日分データを取得・保存
- 10分ごとに `google_calendar_freebusy.main()` を呼び free/busy CSV を更新
- free の時間帯にいるとき、以下の条件で Slack 通知:
  * 直近1分の歩数が前回比で +50 以上
  * または、free 時間内で歩数が連続20分間 0 の場合

設計方針:
- テスト実行のため、通知抑止は行わない（発生するたび送る）。将来は suppression を簡単に追加できるよう設計。
- Slack トークン/チャンネルは既存の `slack_test.py` 内の値を読み取り再利用する（import で自動送信しないよう直接ファイルを読み解析する）。

使い方（テスト）:
  python main.py

注意: 実行には`fitbit_sampler.py`と`google_calendar_freebusy.py`が正しく動作すること（tokens.db にトークンがあること）が前提です。
"""

import threading
import time
import logging
import logging.handlers
import sys
import signal
import json
from datetime import datetime, timedelta
import csv
import os
import re
from typing import Any, Dict, List, Tuple, Optional

REPO_ROOT = os.path.dirname(os.path.abspath(__file__))
LOCKS_DIR = os.path.join(REPO_ROOT, 'locks')

# Load .env into environment early so modules that read env see values.
def _load_dotenv(path='.env'):
    """Read simple KEY=VALUE lines from .env and set os.environ for missing keys.
    If DATABASE_URL is not present but POSTGRES_* vars exist, construct DATABASE_URL
    and append it to the .env file so future runs see it.
    """
    try:
        if not os.path.exists(path):
            return
        existing = {}
        with open(path, 'r', encoding='utf-8') as f:
            for ln in f:
                ln = ln.strip()
                if not ln or ln.startswith('#') or '=' not in ln:
                    continue
                k, v = ln.split('=', 1)
                k = k.strip()
                v = v.strip().strip('"').strip("'")
                existing[k] = v
                # only set if not already in environment
                os.environ.setdefault(k, v)

        # ensure DATABASE_URL exists when Postgres pieces are present
        if not os.environ.get('DATABASE_URL'):
            user = os.environ.get('POSTGRES_USER') or existing.get('POSTGRES_USER')
            pwd = os.environ.get('POSTGRES_PASSWORD') or existing.get('POSTGRES_PASSWORD')
            dbn = os.environ.get('POSTGRES_DB') or existing.get('POSTGRES_DB')
            host = os.environ.get('POSTGRES_HOST') or existing.get('POSTGRES_HOST') or 'localhost'
            port = os.environ.get('POSTGRES_PORT') or existing.get('POSTGRES_PORT') or '5432'
            if user and pwd and dbn:
                dsn = f'postgresql://{user}:{pwd}@{host}:{port}/{dbn}'
                os.environ['DATABASE_URL'] = dsn
                # append to .env for persistence
                try:
                    with open(path, 'a', encoding='utf-8') as f:
                        f.write('\n# auto-generated by main.py\n')
                        f.write('DATABASE_URL=' + dsn + '\n')
                except Exception:
                    pass
    except Exception:
        # never fail startup due to .env parsing
        pass


# load .env now
_load_dotenv()

from db import connect as db_connect
try:
    import portalocker
except Exception:
    portalocker = None
    # Informative message: portalocker is optional but recommended for cross-process file locks
    try:
        print('Warning: optional package "portalocker" is not installed. File-based locks will fall back to less robust in-process locking. Install with: pip install portalocker')
    except Exception:
        pass

import fitbit_sampler
import storage_sqlite
import google_calendar_freebusy
import tokens_db
import slack_notifier
import send_slack_checkbox
import lock_db
import fitbit_sleep

# Configurable parameters
# default single user fallback; prefer reading users from DB at runtime
USER_ID = 'seiichirou019@gmail.com'
SAMPLE_INTERVAL = 60  # seconds
CALENDAR_INTERVAL = 10 * 60  # seconds
FULLDAY_INTERVAL = 60  # seconds (every 1 minute)
FREEBUSY_CSV_DIR = os.path.join('data_output', 'date')
VALUE_JSON_DIR = os.path.join('data_output', 'value')
LOG_PATH = os.path.join('logs', 'main.log')
# notification cooldown in seconds (default 2 hours　2 * 60 * 60)
NOTIFY_COOLDOWN_SECONDS = 2 * 60 * 60

# Process-level restart flag used for self-healing when critical worker threads stop.
_RESTART_REQUESTED = False
_RESTART_REASON = None
_MANUAL_STOP_REQUESTED = False


def request_process_restart(reason: str):
    global _RESTART_REQUESTED, _RESTART_REASON
    if _MANUAL_STOP_REQUESTED:
        return
    if _RESTART_REQUESTED:
        return
    _RESTART_REQUESTED = True
    _RESTART_REASON = reason
    logging.critical('Process restart requested: %s', reason)


# ログ設定: ローテーション付きのファイルハンドラとコンソール出力を設定します。
# プロセスやスレッドがクラッシュしても致命的な例外がログに残るようにしています。
os.makedirs(os.path.dirname(LOG_PATH), exist_ok=True)

# ルートロガーを設定
root_logger = logging.getLogger()
root_logger.setLevel(logging.INFO)

# ローテーティングファイルハンドラ（1ファイルあたり5MB、バックアップ10個）
rot_handler = logging.handlers.RotatingFileHandler(LOG_PATH, maxBytes=5 * 1024 * 1024, backupCount=10, encoding='utf-8')
rot_handler.setFormatter(logging.Formatter('%(asctime)s %(levelname)s: %(message)s'))
root_logger.addHandler(rot_handler)

# コンソール出力ハンドラ
console = logging.StreamHandler()
console.setLevel(logging.INFO)
console.setFormatter(logging.Formatter('%(asctime)s %(levelname)s: %(message)s'))
root_logger.addHandler(console)


# Optional: enable very verbose Slack / HTTP / websocket debug logging when requested
if os.environ.get('DEBUG_SLACK') in ('1', 'true', 'True'):
    try:
        slack_log_path = os.path.join('logs', 'slack_debug.log')
        debug_handler = logging.handlers.RotatingFileHandler(slack_log_path, maxBytes=2 * 1024 * 1024, backupCount=5, encoding='utf-8')
        debug_handler.setLevel(logging.DEBUG)
        debug_handler.setFormatter(logging.Formatter('%(asctime)s %(name)s %(levelname)s: %(message)s'))
        # attach to several loggers used by Slack/HTTP stacks
        for logger_name in ('slack_bolt', 'slack_sdk', 'urllib3', 'websockets', 'websocket', 'httpx', 'httpcore'):
            lg = logging.getLogger(logger_name)
            lg.setLevel(logging.DEBUG)
            lg.addHandler(debug_handler)
        root_logger.info('DEBUG_SLACK enabled: detailed Slack/HTTP logs will be written to %s', slack_log_path)
    except Exception:
        logging.exception('Failed to enable DEBUG_SLACK logging')


# メインスレッドでキャッチされない例外をログに残すフック
def _log_unhandled_exception(exc_type, exc_value, exc_tb):
    # KeyboardInterrupt は標準の挙動に任せる
    if exc_type is KeyboardInterrupt:
        sys.__excepthook__(exc_type, exc_value, exc_tb)
        return
    logging.critical('未捕捉例外', exc_info=(exc_type, exc_value, exc_tb))

sys.excepthook = _log_unhandled_exception


# スレッド内での未捕捉例外をログに残す（Python 3.8+ の場合）
def _thread_excepthook(args):
    try:
        # args は exc_type, exc_value, exc_traceback, thread を含む
        logging.critical('スレッド内で未捕捉例外: %s', getattr(args, 'thread', None), exc_info=(args.exc_type, args.exc_value, args.exc_traceback))
    except Exception:
        logging.exception('threading.excepthook 処理中にエラー')

try:
    threading.excepthook = _thread_excepthook
except Exception:
    # 古い Python では threading.excepthook が存在しないため無視
    pass


# プロセス終了シグナルを受け取ったらログを残して終了する
def _handle_signal(signum, frame):
    global _MANUAL_STOP_REQUESTED
    _MANUAL_STOP_REQUESTED = True
    logging.info('シグナル %s 受信、終了します', signum)
    # ハンドラをフラッシュ
    for h in list(logging.getLogger().handlers):
        try:
            h.flush()
        except Exception:
            pass
    sys.exit(0)

try:
    signal.signal(signal.SIGTERM, _handle_signal)
    signal.signal(signal.SIGINT, _handle_signal)
except Exception:
    # Windows や制限環境では例外が出る場合があるが安全に無視
    pass


def read_free_intervals_for_today(user_id: Optional[str] = None) -> List[Tuple[datetime, datetime]]:
    """当日の freebusy CSV を読み、(開始, 終了) のタイムゾーン付き datetime リストを返す。
    ファイルが無ければ空リストを返す。
    """
    today_tag = datetime.now().strftime('%Y-%m-%d')
    # per-user freebusy CSV: data_output/<sanitized_user>/date/freebusy_YYYY-MM-DD.csv
    if user_id:
        try:
            safe = storage_sqlite._sanitize_user_id(user_id)
            path = os.path.join('data_output', safe, 'date', f'freebusy_{today_tag}.csv')
        except Exception:
            path = os.path.join(FREEBUSY_CSV_DIR, f'freebusy_{today_tag}.csv')
    else:
        path = os.path.join(FREEBUSY_CSV_DIR, f'freebusy_{today_tag}.csv')
    if not os.path.exists(path):
        return []
    intervals = []
    with open(path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for r in reader:
            try:
                # prefer start_local / end_local if present with tz
                s = r.get('start_local') or r.get('start_iso')
                e = r.get('end_local') or r.get('end_iso')
                # try parse with timezone
                try:
                    start_dt = datetime.strptime(s, '%Y-%m-%d %H:%M %z')
                except Exception:
                    try:
                        start_dt = datetime.fromisoformat(s)
                    except Exception:
                        start_dt = datetime.strptime(s, '%Y-%m-%d %H:%M')
                        start_dt = start_dt.replace(tzinfo=datetime.now().astimezone().tzinfo)
                try:
                    end_dt = datetime.strptime(e, '%Y-%m-%d %H:%M %z')
                except Exception:
                    try:
                        end_dt = datetime.fromisoformat(e)
                    except Exception:
                        end_dt = datetime.strptime(e, '%Y-%m-%d %H:%M')
                        end_dt = end_dt.replace(tzinfo=datetime.now().astimezone().tzinfo)
                intervals.append((start_dt, end_dt))
            except Exception:
                continue
    return intervals



def detect_events(parsed: List[Tuple[datetime, Any, Any]], now: datetime, curr_interval: Tuple[datetime, datetime],
                  threshold_steps: int = 20) -> List[Dict[str, Any]]:
    """Detect increase and no-movement events from parsed samples."""
    events = []
    try:
        if not parsed:
            return events
        parsed_sorted = sorted(parsed, key=lambda x: x[0])

        # detect increase anchored at last HR-present
        last_hr_idx = None
        for i in range(len(parsed_sorted) - 1, -1, -1):
            if parsed_sorted[i][1] is not None:
                last_hr_idx = i
                break
        if last_hr_idx is not None:
            last_hr_ts = parsed_sorted[last_hr_idx][0]
            window_start = last_hr_ts - timedelta(minutes=5)
            window = [p for p in parsed_sorted if window_start <= p[0] <= last_hr_ts]
            window.sort(key=lambda x: x[0])
            for j in range(1, len(window)):
                prev = window[j - 1]
                curr = window[j]
                prev_steps = prev[2]
                curr_steps = curr[2]
                if isinstance(prev_steps, (int, float)) and isinstance(curr_steps, (int, float)):
                    if curr_steps - prev_steps >= threshold_steps:
                        events.append({
                            'type': 'increase',
                            'ts': curr[0],
                            'prev_steps': prev_steps,
                            'curr_steps': curr_steps,
                            'diff': curr_steps - prev_steps,
                        })
                        break

        # detect no-movement: contiguous 10-sample block ending at last HR-present
        if len(parsed_sorted) >= 10:
            last_hr_idx = None
            for i in range(len(parsed_sorted) - 1, -1, -1):
                if parsed_sorted[i][1] is not None:
                    last_hr_idx = i
                    break
            if last_hr_idx is not None and last_hr_idx >= 9:
                block_start = last_hr_idx - 9
                block = parsed_sorted[block_start:last_hr_idx + 1]
                all_zero = True
                for ts, hr, steps in block:
                    if not (curr_interval[0] <= ts <= curr_interval[1]):
                        all_zero = False
                        break
                    if not isinstance(steps, (int, float)) or steps != 0:
                        all_zero = False
                        break
                if all_zero:
                    events.append({'type': 'no_movement', 'ts': parsed_sorted[last_hr_idx][0]})
    except Exception:
        logging.exception('detect_events failed')
    return events


def evaluate_parsed_and_enqueue(user_id: str, parsed: list, now: datetime, curr_interval: Tuple[datetime, datetime], slack_cfg):
    """Detect events and launch the checkbox survey session for each eligible event."""
    try:
        try:
            if fitbit_sleep.is_in_median_sleep_window(user_id, now, max_items=14):
                logging.info('Median sleep window suppression: user=%s', user_id)
                return
        except Exception:
            logging.exception('Median sleep window check failed for user=%s; continuing notifications', user_id)

        events = detect_events(parsed, now, curr_interval)
        channel = slack_cfg[1] if slack_cfg else None
        for ev in events:
            # Determine detection_type based on event
            if ev.get('type') == 'no_movement':
                detection_type = 'no_movement'
                recommended_types = ['stretch', 'strength']
            else:
                detection_type = 'motion'
                recommended_types = ['cardio', 'strength']

            # AI will choose the actual exercise type from recommended_types;
            # use recommended_types[0] only as a label/fallback before the AI responds.
            fallback_exercise_type = recommended_types[0]

            # Build AI context (may read DB but doesn't modify send state)
            try:
                ai_context = storage_sqlite.build_exercise_ai_input(
                    user_id=user_id,
                    exercise_type=fallback_exercise_type,
                    exercise_name=None,
                    event={
                        'type': ev.get('type'),
                        'ts': ev.get('ts'),
                    },
                    limit=5,
                )
            except Exception:
                logging.exception('Failed to build exercise AI input for user=%s', user_id)
                ai_context = {
                    'exercise_type': fallback_exercise_type,
                    'motion_detected': ev.get('type') != 'no_movement',
                    'detected_event_type': ev.get('type'),
                    'detected_at': ev.get('ts').isoformat() if ev.get('ts') and hasattr(ev.get('ts'), 'isoformat') else None,
                    'pre_survey': {'visibility': None},
                    'recent_exercises': [],
                    'adherence_by_type': [],
                }

            # Add detection_type and recommended_types to AI context
            ai_context['detection_type'] = detection_type
            ai_context['recommended_types'] = recommended_types

            # Critical section: serialize per-user actions and enforce cooldown
            # for both motion and no_movement paths to avoid duplicate launches.
            try:
                with storage_sqlite.user_lock(user_id):
                    # Re-check last sent time under lock to avoid races
                    last_sent = storage_sqlite.get_last_sent_time(user_id)
                    allow = True
                    if last_sent:
                        try:
                            diff = datetime.now().astimezone() - last_sent
                            if diff.total_seconds() < NOTIFY_COOLDOWN_SECONDS:
                                allow = False
                        except Exception:
                            allow = True
                    if not allow:
                        continue

                    # If this is a no_movement detection, launch the interactive pre-survey
                    # session which will handle pre-survey -> exercise message -> post-survey
                    # in a separate process.
                    if detection_type == 'no_movement':
                        try:
                            # channel may be None if slack_cfg missing; guard the call
                            try:
                                send_slack_checkbox.launch_session(
                                    user_id=user_id,
                                    channel=channel,
                                    motion_detected=False,
                                    exercise_type=fallback_exercise_type,
                                    ai_context=ai_context,
                                    detection_type=detection_type,
                                )
                            except TypeError:
                                # older launch_session signatures may not accept kwargs
                                send_slack_checkbox.launch_session(user_id, channel, False, fallback_exercise_type, ai_context, detection_type)
                        except Exception:
                            logging.exception('Failed to launch send_slack_checkbox session for no_movement')
                        # Skip the enqueue path since interactive flow will send message
                        continue

                    # motion detection path: AI picks exercise type from recommended_types.
                    message_text = send_slack_checkbox._fallback_exercise_message(
                        fallback_exercise_type,
                        detection_type,
                    )
                    try:
                        ai_payload = send_slack_checkbox._generate_exercise_payload(
                            user_id=user_id,
                            exercise_type=fallback_exercise_type,
                            pre_survey={},
                            ai_context=ai_context if isinstance(ai_context, dict) else None,
                            detection_type=detection_type,
                        )
                        # Use AI-chosen category if returned; otherwise fall back.
                        chosen_exercise_type = ai_payload.get('category') if isinstance(ai_payload, dict) else None
                        if chosen_exercise_type not in ('stretch', 'cardio', 'strength'):
                            chosen_exercise_type = fallback_exercise_type
                        chosen_exercise_name = ai_payload.get('exercise_name') if isinstance(ai_payload, dict) else None
                        if not isinstance(chosen_exercise_name, str) or not chosen_exercise_name.strip():
                            chosen_exercise_name = send_slack_checkbox._exercise_name(chosen_exercise_type)
                        message_text = ai_payload.get('message') if isinstance(ai_payload, dict) else None
                        if not isinstance(message_text, str) or not message_text.strip():
                            message_text = send_slack_checkbox._fallback_exercise_message(
                                chosen_exercise_type,
                                detection_type,
                            )

                        nid = storage_sqlite.create_sent_notification(
                            user_id=user_id,
                            exercise_name=chosen_exercise_name,
                            exercise_type=chosen_exercise_type,
                            message_text=message_text,
                            ai_category=ai_payload.get('category') if isinstance(ai_payload, dict) else None,
                            ai_rationale=ai_payload.get('rationale') if isinstance(ai_payload, dict) else None,
                            reps=ai_payload.get('reps') if isinstance(ai_payload, dict) else None,
                            sets=ai_payload.get('sets') if isinstance(ai_payload, dict) else None,
                            duration_min=ai_payload.get('duration_min') if isinstance(ai_payload, dict) else None,
                            detection_type=detection_type,
                            ai_context=ai_context if isinstance(ai_context, dict) else None,
                        )
                        storage_sqlite.create_pending_response(nid, user_id)
                    except Exception:
                        logging.exception('Failed to create sent notification record')
                        chosen_exercise_type = fallback_exercise_type
                        nid = None

                    # Enqueue message with post-survey blocks so users can answer implementation/adherence.
                    # For motion detection, include the generated exercise message inside blocks
                    # (first section) so Slack shows message -> questionnaire in that order.
                    try:
                        motion_blocks = []
                        if message_text:
                            motion_blocks.append({
                                'type': 'section',
                                'text': {'type': 'mrkdwn', 'text': message_text},
                            })
                        motion_blocks.extend(send_slack_checkbox.build_post_survey_blocks(chosen_exercise_type))
                        payload = json.dumps(motion_blocks, ensure_ascii=False)
                        storage_sqlite.enqueue_notification_for_user(
                            user_id,
                            message_text or '運動を実施しましたか？',
                            notification_id=nid,
                            payload=payload,
                        )
                    except Exception:
                        logging.exception('Failed to enqueue notification for user=%s', user_id)
            except Exception:
                logging.exception('Failed during locked enqueue for user=%s', user_id)
    except Exception:
        logging.exception('evaluate_parsed_and_enqueue (wrapper) failed')


class Sampler:
    # per-user context object; sample_once の廃止に伴い履歴保持は不要になった
    def __init__(self, user_id: str):
        self.user_id = user_id


def calendar_updater(stop_event: threading.Event, users: List[str]):
    """スレッド: CALENDAR_INTERVAL 秒ごとにカレンダーの free/busy CSV を更新する（ユーザごとに google_calendar_freebusy.main を呼ぶ）。"""
    logging.info('Calendar updater started (interval=%s sec)', CALENDAR_INTERVAL)
    while not stop_event.is_set():
        for user in users:
            try:
                logging.info('Calendar update starting for %s', user)
                google_calendar_freebusy.main(account_id=user)
                logging.info('Calendar update succeeded for %s', user)
            except Exception:
                logging.exception('Calendar update failed for user=%s', user)
        # wait
        stop_event.wait(CALENDAR_INTERVAL)


def get_users_from_db() -> List[str]:
    """Return a list of user IDs to process. Prefer `fitbit_tokens.user_id`, fall back to google_calendar_tokens.account_id."""
    # No local SQLite fallback: rely on central Postgres via db.connect()
    db = os.environ.get('TOKEN_DB') or os.environ.get('FITBIT_TOKEN_DB') or None
    users = []
    try:
        # use db.connect() which will connect to DATABASE_URL if set
        conn = db_connect()
        cur = conn.cursor()
        try:
            cur.execute('SELECT DISTINCT user_id FROM fitbit_tokens')
            rows = cur.fetchall()
            users = [r[0] for r in rows if r and r[0]]
        except Exception:
            users = []
        if not users:
            try:
                cur.execute('SELECT DISTINCT account_id FROM google_calendar_tokens')
                rows = cur.fetchall()
                users = [r[0] for r in rows if r and r[0]]
            except Exception:
                users = []
    except Exception:
        logging.exception('Failed to read users from DB')
        users = []
    finally:
        try:
            conn.close()
        except Exception:
            pass
    return users


def full_day_updater(stop_event: threading.Event, user_id: str):
    """スレッド: 定期的に1日の per-minute データを取得し、日次 JSON に保存（マージ）する。"""
    logging.info('Full-day updater started (interval=%s sec)', FULLDAY_INTERVAL)
    while not stop_event.is_set():
        try:
            today = datetime.now().strftime('%Y-%m-%d')
            logging.info('Full-day fetch for %s', today)
            per_minute, summary = fitbit_sampler.fetch_day(user_id, today, include_summary=True)
            saved = fitbit_sampler.save_day_json(
                user_id,
                today,
                per_minute,
                out_dir=VALUE_JSON_DIR,
                resting_heart_rate=(summary or {}).get('resting_heart_rate'),
            )
            logging.info('Saved day file: %s', saved)
            # optionally upsert into DB so full-day fetch fills missing values saved as NULL by realtime
            # Disabled by default to avoid unexpected writes; enable by setting env FULLDAY_UPSERT_ENABLED=1
            try:
                if os.environ.get('FULLDAY_UPSERT_ENABLED', '0') == '1':
                    try:
                        storage_sqlite.upsert_samples_from_per_minute(user_id, today, per_minute)
                    except Exception:
                        logging.exception('Failed to upsert full-day samples into DB')
            except Exception:
                logging.exception('Full-day DB upsert encountered error')
        except Exception:
            logging.exception('Full-day update failed')
        stop_event.wait(FULLDAY_INTERVAL)


def _notifier_loop(stop_event: threading.Event, interval: int = 5):
    """通知キューを定期的にポーリングして notifier_worker に処理を委譲するデーモンスレッド用ループ。"""
    try:
        import notifier_worker
    except Exception:
        logging.exception('Notifier module not available; notifier loop exiting')
        return
    logging.info('Notifier loop started (interval=%s sec)', interval)
    while not stop_event.is_set():
        try:
            notifier_worker.process_batch(limit=10, do_send=True)
        except Exception:
            logging.exception('Notifier loop error')
        stop_event.wait(interval)


def sampler_loop(sampler: Sampler, stop_event: threading.Event, slack_cfg):
    logging.info('Sampler loop started (interval=%s sec)', SAMPLE_INTERVAL)
    while not stop_event.is_set():
        now = datetime.now().astimezone()
        try:
            fitbit_sleep.refresh_recent_sleep_history_if_due(sampler.user_id, now)

            # Evaluate events only during free intervals. Per-minute samples are
            # collected by full_day_updater and written to the same day JSON file.
            intervals = read_free_intervals_for_today(sampler.user_id)
            in_free = False
            curr_interval = None
            for s, e in intervals:
                if s <= now <= e:
                    in_free = True
                    curr_interval = (s, e)
                    break
            if in_free and curr_interval:
                # Use recent samples (day JSON file) within last 60 minutes for decisions
                try:
                    recent_rows = storage_sqlite.get_recent_samples(sampler.user_id, minutes=60)
                except Exception:
                    logging.exception('Failed to get recent samples')
                    recent_rows = []

                # normalize recent_rows to list of (ts(datetime), heart_rate, steps)
                parsed = []
                for r in recent_rows:
                    try:
                        ts = datetime.fromisoformat(r[0])
                        parsed.append((ts, r[1], r[2]))
                    except Exception:
                        continue

                # evaluate parsed samples using shared logic
                evaluate_parsed_and_enqueue(sampler.user_id, parsed, now, curr_interval, slack_cfg)
        except Exception:
            logging.exception('Evaluation failed')
        # wait until next sample
        stop_event.wait(SAMPLE_INTERVAL)


def main():
    global _RESTART_REQUESTED, _RESTART_REASON, _MANUAL_STOP_REQUESTED
    # Reset process-level control flags for each fresh main() run.
    _RESTART_REQUESTED = False
    _RESTART_REASON = None
    _MANUAL_STOP_REQUESTED = False
    # load slack config
    # channel mapping is stored in tokens.db; bot token is read from slack_test.py
    token = None
    # load slack token from slack_notifier (env or module constants)
    token_cfg = slack_notifier.get_slack_config()
    if token_cfg:
        token = token_cfg[0]

    # determine users to process from DB (fitbit_tokens preferred)
    users = get_users_from_db()
    if not users:
        users = [USER_ID]
    logging.info('Users to process: %s', users)

    # per-user samplers
    samplers = {u: Sampler(u) for u in users}

    # Ensure DB schema / PRAGMA for better concurrency
    try:
        storage_sqlite.ensure_schema()
    except Exception:
        logging.exception('Failed to ensure DB schema')
    
    # normal continuous mode
    stop_event = threading.Event()

    # start calendar updater (single)
    cal_thread = threading.Thread(target=calendar_updater, args=(stop_event, users), daemon=True)
    cal_thread.start()

    # start per-user full-day and sampler threads
    user_threads = []
    for user, sampler in samplers.items():
        # per-user slack cfg
        channel = tokens_db.get_channel_for_user(user)
        if not channel:
            logging.warning('Slack channel not found in tokens.db for user=%s; notifications may be disabled for this user', user)
        if not token:
            logging.warning('Slack bot token not found in slack_notifier; notifications will be disabled')
        slack_cfg_user = (token, channel) if token and channel else None

        t_full = threading.Thread(target=full_day_updater, args=(stop_event, user), daemon=True)
        t_full.start()
        user_threads.append(t_full)

        t_samp = threading.Thread(target=sampler_loop, args=(sampler, stop_event, slack_cfg_user), daemon=True)
        t_samp.start()
        user_threads.append(t_samp)

    # start notifier loop only when central socket_server is not running.
    # Keeping a single sender process avoids duplicate Slack posts for one DB queue item.
    notifier_thread = None
    try:
        socket_server_running = lock_db.is_held('socket_server')
    except Exception:
        socket_server_running = False

    if socket_server_running:
        logging.info('socket_server DB lock detected; skip main notifier loop')
    else:
        notifier_thread = threading.Thread(target=_notifier_loop, args=(stop_event,), daemon=True)
        notifier_thread.start()

    logging.info('main: running. press Ctrl+C to stop')
    try:
        while True:
            if not cal_thread.is_alive():
                request_process_restart('calendar_updater thread stopped unexpectedly')
                break
            time.sleep(1)
    except KeyboardInterrupt:
        _MANUAL_STOP_REQUESTED = True
        logging.info('Stopping...')
    finally:
        if _MANUAL_STOP_REQUESTED:
            # Manual stop always wins over automatic self-restart.
            _RESTART_REQUESTED = False
            _RESTART_REASON = None
        stop_event.set()
        cal_thread.join(timeout=5)
        for t in user_threads:
            try:
                t.join(timeout=5)
            except Exception:
                pass
        if notifier_thread is not None:
            notifier_thread.join(timeout=5)

    return _RESTART_REQUESTED


if __name__ == '__main__':
    # Acquire single-instance DB lock to avoid multiple Socket Mode clients
    try:
        lock_owner = lock_db.make_owner()
        if not lock_db.acquire('main', lock_owner):
            logging.error('Another instance appears to be running (DB lock main is held). Exiting.')
            sys.exit(1)
        heartbeat_stop = lock_db.start_heartbeat('main', lock_owner)

        should_restart = False
        try:
            should_restart = main()
        finally:
            heartbeat_stop.set()
            lock_db.release('main', lock_owner)

        if should_restart:
            try:
                logging.critical('Restarting main process now. reason=%s', _RESTART_REASON)
            except Exception:
                pass
            os.execv(sys.executable, [sys.executable] + sys.argv)
    except SystemExit:
        raise
    except Exception:
        logging.exception('Failed to start main with instance lock')
